import * as fs from "fs";
import * as path from "path";
import {
  parseFrontmatter,
  extractOrderFromFilename,
  generateContentHash,
} from "../utils/markdown";
import type { KnowledgeChunk, KnowledgeDomain } from "../contracts";

/**
 * ─────────────────────────────────────────────────────────────────
 * INGESTION BOUNDARY: website/docs/
 *
 * Why this directory and nothing else?
 *
 *  1. website/docs/ contains the canonical, build-output markdown
 *     files produced by build_docs.py.  These are the exact same
 *     files that Docusaurus renders on the live site.
 *
 *  2. Ingesting from here (NOT website/sources/, NOT the repo root)
 *     guarantees the AI answers from the same content the user sees,
 *     eliminating drift between the docs site and the knowledge API.
 *
 *  3. Each file is already split to an appropriate granularity by
 *     build_docs.py (one file per whitepaper section).  We treat
 *     each file as ONE canonical chunk — no re-splitting by headings.
 *
 *  Excluded paths (and why):
 *    - website/sources/    → raw authoring source, not canonical
 *    - .docusaurus/        → Docusaurus cache, not content
 *    - node_modules/       → dependencies, not content
 *    - Root-level scripts  → tooling, not documentation
 * ─────────────────────────────────────────────────────────────────
 */

/**
 * Relative path from repo root to the canonical docs directory.
 * Tries website/docs first (monorepo layout), then docs (root-level layout).
 */
export function getDocsDir(repoRoot: string): string {
  const websiteDocs = path.join(repoRoot, "website", "docs");
  const rootDocs = path.join(repoRoot, "docs");
  if (fs.existsSync(websiteDocs)) return websiteDocs;
  if (fs.existsSync(rootDocs)) return rootDocs;
  return websiteDocs; // fallback for error message
}

/** The Docusaurus route prefix for the whitepaper docs */
const WHITEPAPER_ROUTE_BASE = "/whitepaper";

/**
 * Ingest all canonical markdown files from website/docs/.
 *
 * Each .md file becomes exactly one KnowledgeChunk.  Metadata is
 * extracted from frontmatter (generated by build_docs.py), ensuring
 * slugs and titles match what Docusaurus renders.
 *
 * @param repoRoot - Absolute path to the repository root.
 * @returns Array of KnowledgeChunks, one per file, sorted by document order.
 */
export async function ingestCanonicalDocs(
  repoRoot: string,
): Promise<KnowledgeChunk[]> {
  const docsDir = getDocsDir(repoRoot);

  if (!fs.existsSync(docsDir)) {
    throw new Error(
      `Ingestion boundary directory not found: ${docsDir}\n` +
        `Run "python build_docs.py" (or python3) first to generate canonical docs.`,
    );
  }

  // Read only .md files directly in website/docs/ (flat — no recursion needed).
  // Alphabetical sort preserves the numeric prefix order (00-, 01-, 02-, ...).
  const files = fs
    .readdirSync(docsDir)
    .filter((f) => f.endsWith(".md"))
    .sort();

  const chunks: KnowledgeChunk[] = [];
  const domain: KnowledgeDomain = "docs:whitepaper";

  for (const filename of files) {
    const filepath = path.join(docsDir, filename);
    const raw = fs.readFileSync(filepath, "utf-8");

    const { metadata, body } = parseFrontmatter(raw);

    // Skip empty documents
    const trimmedBody = body.trim();
    if (!trimmedBody) continue;

    // ── Title ────────────────────────────────────────────────
    // Prefer frontmatter title (set by build_docs.py),
    // fall back to the first heading in the body, then filename.
    const title =
      (metadata.title as string) ||
      extractFirstHeading(trimmedBody) ||
      filename.replace(/\.md$/, "");

    // ── Order ────────────────────────────────────────────────
    // Prefer sidebar_position from frontmatter (numeric),
    // fall back to the leading number in the filename prefix.
    const order =
      typeof metadata.sidebar_position === "number"
        ? metadata.sidebar_position
        : extractOrderFromFilename(filename);

    // ── Source path ──────────────────────────────────────────
    // Build the Docusaurus URL for this document.
    // Uses the frontmatter slug (preferred) or id as the URL segment.
    const slug =
      (metadata.slug as string) ||
      (metadata.id as string) ||
      filename.replace(/\.md$/, "");
    const sourcePath = `${WHITEPAPER_ROUTE_BASE}/${slug}`;

    chunks.push({
      content: trimmedBody,
      domain,
      sourcePath,
      title,
      order,
      content_hash: generateContentHash(trimmedBody),
      last_updated: new Date().toISOString(),
    });
  }

  // Sort by order to guarantee document sequence
  chunks.sort((a, b) => a.order - b.order);

  return chunks;
}

/**
 * Extract the first markdown heading from body text.
 * Used as a fallback when frontmatter title is missing.
 */
function extractFirstHeading(body: string): string | null {
  const match = body.match(/^#{1,6}\s+(.+)$/m);
  return match ? match[1].trim() : null;
}
