/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "P2P Foundation Docs",
  "tagline": "Documentation for P2P Foundation",
  "favicon": "img/favicon.svg",
  "url": "https://docs.p2p.me",
  "baseUrl": "/",
  "customFields": {
    "knowledgeApiUrl": "http://localhost:3001"
  },
  "onBrokenLinks": "warn",
  "headTags": [
    {
      "tagName": "link",
      "attributes": {
        "rel": "icon",
        "type": "image/svg+xml",
        "href": "/img/favicondark.svg",
        "media": "(prefers-color-scheme: light)"
      }
    },
    {
      "tagName": "link",
      "attributes": {
        "rel": "icon",
        "type": "image/svg+xml",
        "href": "/img/favicon.svg",
        "media": "(prefers-color-scheme: dark)"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:title",
        "content": "P2P Foundation Docs"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:description",
        "content": "Documentation for P2P Foundation"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:image",
        "content": "https://firebasestorage.googleapis.com/v0/b/p2px-421205.appspot.com/o/user-app%2Fv2%2Fimages%2Fthumbnails%2FfoundationWebsitePreview.png?alt=media&token=b9776f2a-a5c1-43ef-a8cb-764524e16fe4"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:type",
        "content": "website"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "property": "og:url",
        "content": "https://docs.p2p.me"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:card",
        "content": "summary_large_image"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:title",
        "content": "P2P Foundation Docs"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:description",
        "content": "Documentation for P2P Foundation"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "twitter:image",
        "content": "https://firebasestorage.googleapis.com/v0/b/p2px-421205.appspot.com/o/user-app%2Fv2%2Fimages%2Fthumbnails%2FfoundationWebsitePreview.png?alt=media&token=b9776f2a-a5c1-43ef-a8cb-764524e16fe4"
      }
    },
    {
      "tagName": "meta",
      "attributes": {
        "name": "description",
        "content": "Documentation for P2P Foundation"
      }
    }
  ],
  "stylesheets": [
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Outfit:wght@400;500;700&display=swap"
  ],
  "clientModules": [
    "./src/clientModules/tocAutoScroll.js"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars/whitepaper.ts",
          "routeBasePath": "whitepaper"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [],
  "themes": [
    [
      "D:\\work\\Documentation\\node_modules\\@easyops-cn\\docusaurus-search-local\\dist\\server\\server\\index.js",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "indexDocs": true,
        "indexBlog": false,
        "indexPages": false,
        "docsRouteBasePath": [
          "whitepaper"
        ],
        "docsDir": [
          "docs"
        ],
        "searchResultLimits": 10,
        "searchResultContextMaxLength": 50
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "image": "https://firebasestorage.googleapis.com/v0/b/p2px-421205.appspot.com/o/user-app%2Fv2%2Fimages%2Fthumbnails%2FfoundationWebsitePreview.png?alt=media&token=b9776f2a-a5c1-43ef-a8cb-764524e16fe4",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "",
      "logo": {
        "alt": "P2P Foundation",
        "src": "img/p2p-foundation-main.svg",
        "srcDark": "img/p2p-foundation-2.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "whitepaperSidebar",
          "position": "left",
          "label": "Whitepaper"
        },
        {
          "to": "/ai-chat",
          "position": "right",
          "label": "AI Chat"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [],
      "copyright": "\n        <div class=\"footer-row-container\">\n          <div class=\"footer-left\">\n            <img src=\"/img/p2p-logo.svg\" alt=\"P2P Foundation\" class=\"footer-logo\" />\n          </div>\n          <div class=\"footer-center\">\n            <span>© 2026 P2P Foundation.</span>\n          </div>\n          <div class=\"footer-right\">\n            <a href=\"https://discord.gg/p2pfoundation\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-social-link discord\"></a>\n            <a href=\"https://t.me/P2Pdotme\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-social-link telegram\"></a>\n            <a href=\"https://x.com/p2pdotfound\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-social-link twitter\"></a>\n            <a href=\"https://www.youtube.com/@onchainbank\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"footer-social-link youtube\"></a>\n          </div>\n        </div>\n      "
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "scripts": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
